### ISSUE TITLE
follow intro to real world 

### ISSUE THREAD

**Issue by jp-knj** [jp-knj/learn-vue#1]
# Todo
- [x] Intro to Real World Vue
- [x] Vue CLI
- [x] Optimizing your editor
- [ ] Vue Router basics
- [ ] Dynamic Routing & History mode
- [ ] single file vue components
- [ ] global components
- [ ] slots
- [ ] api calls with axios
