### ISSUE TITLE
follow intro to vuex

### ISSUE THREAD

**Issue by jp-knj** [jp-knj/learn-vue#3]
# Todo

- [x] intro to vuex
- [x] mastering vuex orientation
- [x] state and getters
- [x] mutations
- [ ] modules
- [ ] success and error notifications
